// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTClientInfo = "t_client_infos"

// TClientInfo mapped from table <t_client_infos>
type TClientInfo struct {
	ID            int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	IP            string  `gorm:"column:ip" json:"ip"`
	No            string  `gorm:"column:no" json:"no"`
	Ua            string  `gorm:"column:ua" json:"ua"`
	Lang          string  `gorm:"column:lang" json:"lang"`
	Referer       string  `gorm:"column:referer" json:"referer"`
	VisitTime     string  `gorm:"column:visit_time" json:"visit_time"`
	Status        int64   `gorm:"column:status" json:"status"`
	Isp           string  `gorm:"column:isp" json:"isp"`
	Organization  string  `gorm:"column:organization" json:"organization"`
	Country       string  `gorm:"column:country" json:"country"`
	Longitude     float64 `gorm:"column:longitude" json:"longitude"`
	Latitude      float64 `gorm:"column:latitude" json:"latitude"`
	ContinentCode string  `gorm:"column:continent_code" json:"continent_code"`
	CountryCode   string  `gorm:"column:country_code" json:"country_code"`
}

// TableName TClientInfo's table name
func (*TClientInfo) TableName() string {
	return TableNameTClientInfo
}
