// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTGeo = "t_geo"

// TGeo mapped from table <t_geo>
type TGeo struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Code int32  `gorm:"column:code" json:"code"`
	Name string `gorm:"column:name" json:"name"`
	En   string `gorm:"column:en" json:"en"`
	Iso  string `gorm:"column:iso" json:"iso"`
	Icon string `gorm:"column:icon" json:"icon"`
}

// TableName TGeo's table name
func (*TGeo) TableName() string {
	return TableNameTGeo
}
