// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTSchema = "t_schemas"

// TSchema mapped from table <t_schemas>
type TSchema struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	No          string `gorm:"column:no" json:"no"`
	AllowRegion string `gorm:"column:allow_region" json:"allow_region"`
	BanProxy    bool   `gorm:"column:ban_proxy" json:"ban_proxy"`
	DestLink    string `gorm:"column:dest_link" json:"dest_link"`
	BanLink     string `gorm:"column:ban_link" json:"ban_link"`
}

// TableName TSchema's table name
func (*TSchema) TableName() string {
	return TableNameTSchema
}
