// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q           = new(Query)
	TClientInfo *tClientInfo
	TGeo        *tGeo
	TSchema     *tSchema
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	TClientInfo = &Q.TClientInfo
	TGeo = &Q.TGeo
	TSchema = &Q.TSchema
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:          db,
		TClientInfo: newTClientInfo(db, opts...),
		TGeo:        newTGeo(db, opts...),
		TSchema:     newTSchema(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	TClientInfo tClientInfo
	TGeo        tGeo
	TSchema     tSchema
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		TClientInfo: q.TClientInfo.clone(db),
		TGeo:        q.TGeo.clone(db),
		TSchema:     q.TSchema.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		TClientInfo: q.TClientInfo.replaceDB(db),
		TGeo:        q.TGeo.replaceDB(db),
		TSchema:     q.TSchema.replaceDB(db),
	}
}

type queryCtx struct {
	TClientInfo ITClientInfoDo
	TGeo        ITGeoDo
	TSchema     ITSchemaDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		TClientInfo: q.TClientInfo.WithContext(ctx),
		TGeo:        q.TGeo.WithContext(ctx),
		TSchema:     q.TSchema.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
